# Script for bank/name.go

BEGIN {
  print "// Package bank  name generated by script, do not modify directly."
  print "package bank\n"
  print "// BankNameMap standards for Bank abbr and name map"
  print "var BankNameMap = map[string]string{"

  FS=","
}

FNR > 1 {
  if (/^$/) {
    print; next
  }
  fmt = "\"%s\":\"%s\",\n"
  printf fmt, $1, $2
}

END { print "}" }
