# Automatically to generate bank/bin.go

BEGIN {
  print "// Package bank   bin generated by script, do not modify directly."
  print "package bank\n"
  print "// CardBINs card bins"
  print "var CardBINs = [...]*CardBIN{"

  FS=","
}

/^bin/ { next }

/^$/ { 
  print "\n"
  next
}

{ 
  fmt = "&CardBIN{Bin: \"%s\", Bank: \"%s\", Type: \"%s\", Length: %s},\n"
  printf fmt, $1, $2, $3 ,$4
}

END { print "}" }

