# Automatically to generate bank/bin.go

BEGIN {
  print "// This file is generated by script. Do not modify directly.\n"
  print "package bank\n"
  print "// CardBINs card bins"
  print "var CardBINs = [...]*CardBIN{"

  FS=","
}

FNR > 1 {
  if (/^$/) {
    print; next
  }
  fmt = "&CardBIN{Bin: \"%s\", Bank: \"%s\", Type: \"%s\", Length: %s},\n"
  printf fmt, $1, $2, $3 ,$4
}

END { print "}" }
