name: bcbc

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    name: Build & test
    runs-on: ${{ matrix.os }}
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.13.1'
    - run: go version

    - name: Build and test
      run: |
        make all
