name: bcbc-release-bin-wf

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

jobs:
  goreleaser:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.13.1'

    - name: Build bcbc
      run: make build

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}